version: '3.8'

services:
  eureka:
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - 8761:8761

  gateway:
    container_name: cloud-gateway
    build:
      context: ./cloud-gateway
    ports:
      - 8080:8080
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka/"
      EUREKASERVER_PORT: 8761
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: cart
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: lb://CART
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/cart/**

    depends_on:
      eureka:
        condition: service_started

  cart:
      container_name: cart
      build:
        context: ./cart
      ports:
        - 8500:8500
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka/"
        EUREKASERVER_PORT: 8761
        EUREKA_INSTANCE_INSTANCEID: 1
        SERVER_PORT: 8500
      depends_on:
        eureka:
          condition: service_started

    



