spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:mysql://localhost:4306/itp
    username: itp
    password: itp
  application:
    name: cart
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8500